apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tpfoyer
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      containers:
        - name: tpfoyer
          image: amounboukhris/tpfoyer:1.0
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_AUTOCONFIGURE_EXCLUDE
              value: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
